Add cached functions (stub)
Adamant-im/adamant-tradebot pull request #55
Opened 2024-03-28 08:49 UTC by adamant-al

Adding stub cached functions allows to add new modules to client versions of tradebot easier.
Also, these functions includes extended logging.

2024-03-28 09:06 UTC, bludnic requested changes

2024-03-28 09:06 UTC, bludnic commented on trade/orderUtils.js
> +  */
Add params description in the docblock. Also for `getOrderBookCached`

2024-03-28 09:43 UTC, bludnic approved these changes

2024-03-29 17:42 UTC, confleux approved these changes

2024-03-31 08:13 UTC, merged